apiVersion: v1
kind: Service
metadata:
  name: blue-green-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    # This selector determines which deployment receives traffic
    # Change between 'blue-app' and 'green-app' to switch traffic
    app: blue-app  # Initially set to blue
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer